apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend/backend:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db:5432/ideaboard
          ports:
            - containerPort: 4000
